dist: trusty
language: rust
services: docker
sudo: required
addons:
  apt:
    packages:
      - build-essential
      - libudev-dev

env:
  global:
    - CRATE_NAME=rogcat

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-musl
      rust: stable
    - env: TARGET=x86_64-unknown-linux-musl
      rust: beta
    - env: TARGET=x86_64-unknown-linux-musl
      rust: nightly
    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: stable
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: beta
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly
    # Windows
    - env: TARGET=x86_64-pc-windows-gnu
      rust: stable
    - env: TARGET=x86_64-pc-windows-gnu
      rust: beta
    - env: TARGET=x86_64-pc-windows-gnu
      rust: nightly

before_install: set -e

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: REt9wNmve1blcRxVor+nUAaGX09oBqe3HwiEohwAvVus8XGv1OVd9EMa8o08hb24DOnIKV+T4Gr/tsZ8Yro02wZgjX+FhaBTrImu5KRBnQN/ja6ggn99rfnMriPgOGgL/oUd287qzODqe3s+fFv1K7O02Jor4DfWVAxKk3vKn0vJm90FUQ1vb8i+8McESdWibyzBtPyUsdyA+godHazeAVbri+GMVwEkmzFYo22Au4nGZjD4UHYAEP0u7GFKL5naLFbXkHkPo10epZVWQMAFKE/nRxxvgwfENkvvJI6AVOAROFp/lKAexo+fwNROya1gXY9s+T9nUP8mZwmBevE6Kf3PDHIOQilqGeU32NtM/XfNewYU9D5xiAJADrA5oVJlpmo2vqa1Rnz49qwR6PfnLAhJdpmb/qj4B/5UT/pd+nTc8XVFwWZmrO0TXVsQb2Sc6RLT1ZNc2w2+MdIMKqYNqQDUikx3HFHd77HuAU6ML4LhyNWZEi+oyT1NI+UbLBTzebXEOvF4Arpg+Bu/rbWANSsZJ/oPp9fjGDxwzB5eP3qW/hG3WOOiHVaI5IwPsTsTUHR2GzqXUekAT5J7qyb/Sr99MRltHmesrVGeT4lKWHxSjJkwO6TkJdQqmUtIs5NSo166sZno0VmxeHtY1doVA67pglrrCjyBUQ2rJdhygQU=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - /^v\d+\.\d+\.\d+.*$/
    - master
    - 0.3

notifications:
  email:
    on_success: never
