[package]
authors = ["Felix Obenhuber <felix@obenhuber.de>"]
categories = ["command-line-utilities", "development-tools"]
description = "A adb logcat wrapper and log processor"
homepage = "https://github.com/flxo/rogcat"
keywords = ["android", "adb", "debugging", "log", "logcat"]
license = "WTFPL"
name = "rogcat"
readme = "README.md"
repository = "https://github.com/flxo/rogcat"
version = "0.2.15-pre"
[dependencies]
appdirs = "0.2.0"
bytes = "0.4.5"
clap = "2.27.1"
config = "0.7.0"
crc = "1.5.0"
csv = "1.0.0-beta.3"
failure = "0.1.1"
futures = "0.1.17"
handlebars = "0.29.1"
indicatif = "0.8.0"
lazy_static = "0.2.9"
nom = "3.2.1"
rand = "0.3.18"
regex = "0.2.2"
serde = "1.0.19"
serde_derive = "1.0.19"
serde_json = "1.0.6"
serial = "0.4.0"
tempdir = "0.3.5"
term = "0.4.6"
term_size = "0.3.1"
time = "0.1.38"
tokio-core = "0.1.10"
tokio-io = "0.1.4"
tokio-process = "0.1.4"
tokio-signal = "0.1.2"
toml = "0.4.5"
url = "1.6.0"
which = "1.0.3"
zip = "0.2.6"
