[package]
authors = ["Felix Obenhuber <felix@obenhuber.de>"]
categories = [
    "command-line-utilities",
    "development-tools",
]
description = "A adb logcat wrapper and log processor"
homepage = "https://github.com/flxo/rogcat"
keywords = [
    "android",
    "adb",
    "debugging",
    "log",
    "logcat",
]
license = "WTFPL"
name = "rogcat"
readme = "README.md"
repository = "https://github.com/flxo/rogcat"
version = "0.2.17"

[dependencies]
atty = "0.2.11"
bytes = "0.4.10"
clap = "2.32.0"
config = "0.9.1"
crc = "1.8.1"
csv = "1.0.2"
directories = "1.0.2"
failure = "0.1.2"
futures = "0.1.24"
handlebars = "1.0.5"
indicatif = "0.9.0"
lazy_static = "1.1.0"
nom = "4.0.0"
regex = "1.0.5"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.32"
serial = "0.4.0"
term = "0.5.1"
term_size = "0.3.1"
time = "0.1.40"
tokio-core = "0.1.17"
tokio-io = "0.1.9"
tokio-process = "0.2.2"
tokio-signal = "0.2.5"
toml = "0.4.8"
url = "1.7.1"
which = "2.0.0"
zip = "0.4.2"

[dev-dependencies]
rand = "0.5.5"
tempdir = "0.3.7"

[features]
default = []
