[package]
authors = ["Felix Obenhuber <felix@obenhuber.de>"]
name = "rogcat"
version = "0.2.5"

[dependencies]
boolinator = "2.4.0"
clap = "2.16.2"
crc = "*"
csv = "0.15.0"
error-chain = "0.10.0"
futures = "0.1"
handlebars = "0.26.2"
indicatif = "0.5.0"
nom = "2.2.0"
regex = "0.1.73"
serde = "1.0.5"
serde_derive = "1.0.7"
serde_json = "1.0.2"
serial = "0.3.4"
tempdir = "0.3.4"
term-painter = "0.2.3"
time = "0.1.35"
tokio-core = "0.1.7"
tokio-io = "0.1.1"
tokio-process = "0.1.3"
tokio-signal = "*"
which = "0.2.1"
zip = "0.2.3"

[dependencies.terminal_size]
git = "https://github.com/flxo/terminal-size.git"
