[package]
authors = ["Felix Obenhuber <felix@obenhuber.de>"]
description = "A adb logcat wrapper and log processor"
homepage = "https://github.com/flxo/rogcat"
keywords = ["android", "adb", "debugging", "log", "logcat"]
license = "WTFPL"
name = "rogcat"
version = "0.2.7-pre"

[dependencies]
appdirs = "0.2.0"
boolinator = "2.4.0"
clap = "2.16.2"
crc = "1.4.0"
csv = "0.15.0"
error-chain = "0.10.0"
futures = "0.1"
handlebars = "0.26.2"
indicatif = "0.5.0"
lazy_static = "0.2.8"
nom = "2.2.0"
regex = "0.1.73"
serde = "1.0.5"
serde_derive = "1.0.7"
serde_json = "1.0.2"
serial = "0.3.4"
tempdir = "0.3.4"
term-painter = "0.2.3"
term_size = "0.3.0"
time = "0.1.35"
tokio-core = "0.1.7"
tokio-io = "0.1.1"
tokio-process = "0.1.3"
toml = "0.4.2"
which = "0.2.1"
zip = "0.2.3"
