[package]
name = "rogcat"
version = "0.2.2"
authors = ["Felix Obenhuber <felix@obenhuber.de>"]

[dependencies]
clap = "2.16.2"
csv = "0.15.0"
error-chain = "0.10.0"
futures = "0.1"
nom = "2.2.0"
serial = "0.3.4"
regex = "0.1.73"
tempdir = "0.3.4"
term-painter = "0.2.3"
terminal_size = { git = "https://github.com/flxo/terminal-size.git" }
time = "0.1.35"
which = "0.2.1"
