[package]
authors = ["Felix Obenhuber <felix@obenhuber.de>"]
categories = [
    "command-line-utilities",
    "development-tools",
]
description = "A adb logcat wrapper and log processor"
homepage = "https://github.com/flxo/rogcat"
keywords = [
    "android",
    "adb",
    "debugging",
    "log",
    "logcat",
]
license = "WTFPL"
name = "rogcat"
readme = "README.md"
repository = "https://github.com/flxo/rogcat"
version = "0.2.16"

[dependencies]
atty = "0.2.3"
bytes = "0.4.5"
clap = "2.27.1"
config = "0.8.0"
crc = "1.5.0"
csv = "1.0.0-beta.3"
directories = "0.8.4"
failure = "0.1.1"
futures = "0.1.17"
handlebars = "0.32.0"
indicatif = "0.9.0"
lazy_static = "1.0.0"
nom = "3.2.1"
regex = "0.2.2"
serde = "1.0.19"
serde_derive = "1.0.19"
serde_json = "1.0.6"
serial = "0.4.0"
term = "0.5.1"
term_size = "0.3.1"
time = "0.1.38"
tokio-core = "0.1.10"
tokio-io = "0.1.4"
tokio-process = "0.1.4"
tokio-signal = "0.1.2"
toml = "0.4.5"
url = "1.6.0"
which = "1.0.3"
zip = "0.3.0"

[dev-dependencies]
rand = "0.4.0"
tempdir = "0.3.5"

[dependencies.clippy]
optional = true
version = "0.0.190"

[features]
default = []
