[package]
name = "rogcat"
version = "0.2.2"
authors = ["Felix Obenhuber <felix@obenhuber.de>"]

[dependencies]
clap = "2.16.2"
error-chain = "0.10.0"
futures = "0.1"
kabuki = { git = "https://github.com/carllerche/kabuki" }
regex = "0.1.73"
tempdir = "0.3.4"
term-painter = "0.2.3"
terminal_size = "0.1.6"
time = "0.1.35"
tokio-core = "0.1"
