on:
  workflow_dispatch:
  push:
    tags:
      - v*

name: Release

jobs:
  check:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: moonrepo/setup-rust@v1
        with:
          profile: minimal
          channel: stable
          cache: false

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo build
        run: cargo build --release

      - name: Copy x86_64-unknown-linux-gnu
        if: matrix.os == 'ubuntu-latest'
        run: cp target/release/rogcat rogcat-x86-64-unknown-linux-gnu

      - name: Copy x86_64-apple-darwin
        if: matrix.os == 'macos-latest'
        run: cp target/release/rogcat rogcat-x86_64-apple-darwin

      - name: Copy x86_64-pc-windows-msvc.exe
        if: matrix.os == 'windows-latest'
        run: cp target/release/rogcat.exe rogcat-x86_64-pc-windows-msvc.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rogcat-*
